# Generated by Django 4.2.8 on 2023-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vacancy', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=55)),
                ('surname', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('date_born', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.CharField(max_length=55)),
                ('professional_experience', models.CharField(max_length=55)),
                ('education', models.CharField(max_length=55)),
            ],
        ),
    ]
