# Generated by Django 4.2.8 on 2023-12-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0002_resume_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='last_name',
            new_name='middle_name',
        ),
    ]
