# Generated by Django 4.2.8 on 2023-12-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vacancy', models.CharField(max_length=55)),
                ('name_company', models.CharField(max_length=55)),
                ('salary', models.PositiveIntegerField()),
                ('required_skills', models.CharField(max_length=55)),
                ('responsibilities', models.CharField(max_length=55)),
                ('address', models.PositiveIntegerField()),
            ],
        ),
    ]
