# Generated by Django 4.2.8 on 2023-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
